# Generated by Django 5.0.3 on 2024-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
